### ISSUE TITLE
Initializing parameters from program 0

### ISSUE THREAD

**Issue by jpcima** [SpotlightKid/cookiecutter-dpf-effect#11]
Hello,

The initialization of plugins is filling the parameter values with the preset 0, I don't think that's right.
Most probably, it's going to put the state in disagreement with the host's parameters, and the potential UI. (unless the host will init parameters or select program)

At least in DPF internally, the editor is not initialized automatically on the program 0.

Probably, it's preferable to initialize with `ranges.def`.
This is a little more awkward to write this way; an example about what I mean. https://git.io/JvUNT

**Comment by SpotlightKid** [comment]
Thanks for bringing this up. I'll have a look at it, as soon as I can, which may be a few days. Ping me, should I forget.

**Comment by SpotlightKid** [comment]
If we use the strategy shown in the `string-machine` code you linked to, I think we can still use the default values set out in preset 0, if we use this line in
`initParameter`:

        parameter.ranges.def = presetCount > 0 ? factoryPresets[0].params[index] : 0.1f;

What do you think?

**Comment by jpcima** [comment]
To share a personal opinion of the matter, I think it more difficult to update the preset array and the parameter separately; especially when the parameter count grows, it's not easy in the defaults array to keep track of what is each item.

**Comment by SpotlightKid** [comment]
Fixed as you suggested as part of dab379902c78f743ad536c6cf5493d1d56846fcc.
