### ISSUE TITLE
Install targets non-working on FreeBSD

### ISSUE THREAD

**Issue by jpcima** [SpotlightKid/cookiecutter-dpf-effect#12]
Hello, FreeBSD has been reported to fail at the `make install` step.
The command `install` does not have identical meaning as GNU for `-d`,`-D` options.

A workaround is to replace `install` with `mkdir` where applicable.
This patch has been reported as working.
https://github.com/linuxmao-org/fogpad-port/pull/3

**Comment by SpotlightKid** [comment]
Sigh, how annoying ... fixed via 11b4388.
