### ISSUE TITLE
Install rules use the wrong extension for .so

### ISSUE THREAD

**Issue by jpcima** [SpotlightKid/cookiecutter-dpf-effect#15]
Hi, the LV2 install should use `$(LIB_EXT)` not `.so`. See this report
https://github.com/linuxmao-org/regrader-port/issues/2

**Comment by SpotlightKid** [comment]
Ah, yes, sorry, this was introduced by a9a8c78a69d5ae5c9db86d0f5511ed6569b3ac58.
