### ISSUE TITLE
'submodules' rule is not really useful

### ISSUE THREAD

**Issue by pdesaulniers** [SpotlightKid/cookiecutter-dpf-effect#18]
`make submodules` ([defined here](https://github.com/SpotlightKid/cookiecutter-dpf-effect/blob/6cafed22fe5055828c371e43630ea2cc884a8c1c/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile#L13-L14)) will fail if submodules have not yet been cloned, which kinda defeats the purpose of this rule...

```
$ make submodules
Makefile:7: dpf/Makefile.base.mk: No such file or directory
make: *** No rule to make target 'dpf/Makefile.base.mk'.  Stop.
```

Should we get rid of this rule? Otherwise, we could handle the "missing `dpf/Makefile.base.mk`" error more gracefully, and print an error message when submodules are missing:

```
DPF not found. Please run "make submodules" to clone the missing submodules, then retry building the plugin.
```

**Comment by SpotlightKid** [comment]
The [post project generation hook](https://github.com/SpotlightKid/cookiecutter-dpf-effect/blob/6cafed22fe5055828c371e43630ea2cc884a8c1c/hooks/post_gen_project.py#L21) adds the DPF submodule, which will also clone it, so the inclusion of `dpf/Makefile.base.mk` works in newly generated projects.

But I'm open to better strategies.

**Comment by pdesaulniers** [comment]
> The post project generation hook adds the DPF submodule, which will also clone it, so the inclusion of dpf/Makefile.base.mk works in newly generated projects.

Indeed! The `No such file` error is more likely to occur when cloning and building an existing DPF plugin which is based on this cookiecutter template. Here is a use-case I had in mind:

1) I run `git clone https://github.com/jpcima/dpf-imgui-example.git` without passing `--recursive`
2) I `cd` into the repo, then run `make`
3) I get this error: `No rule to make target 'dpf/Makefile.base.mk'`
4) I run `make submodules` to fix my blunder

But right now, the `submodules` rule returns the same error :( `No rule to make target 'dpf/Makefile.base.mk'` So, I don't it is very useful in its current state.

One solution could be to add this at the top of the Makefile:

```Makefile
# use a wildcard to avoid 'dpf/Makefile.base.mk: No such file or directory'
include $(wildcard dpf/Makefile.base.mk)

define MISSING_SUBMODULES_ERROR

===============================
Cannot find DPF! Please run "make submodules" to clone the missing submodules, then retry building the plugin.
===============================

endef

# error out if DPF is missing, unless the current rule is 'submodules'
ifneq ($(MAKECMDGOALS), submodules)
ifeq (,$(wildcard dpf/Makefile.base.mk))
    $(error $(MISSING_SUBMODULES_ERROR))
endif
endif
```

Then, my use-case above should work, and the error would look more user friendly. I stole this idea from the x42 plugins: https://github.com/x42/spectra.lv2/blob/4d5a2a2bd39d3dbbe3fd5243d627b4c3de670414/Makefile#L136-L152.

Otherwise, I would suggest simply removing the rule.

**Comment by SpotlightKid** [comment]
I made a PR where I adapted your idea above in a slightly altered form and also made the DPF path configurable: #20
