### ISSUE TITLE
Install rule problem; target directory must exist

### ISSUE THREAD

**Issue by jpcima** [SpotlightKid/cookiecutter-dpf-effect#9]
In continous build configuration with Ubuntu Trusty, I have this problem,
When running `make install` as the root user, there are messages like this:

```
# install -D -m755 bin/stone-phaser-vst.so -t /usr/local/lib/vst
install: failed to access '/usr/local/lib/vst': No such file or directory
```

it's because regardless of the `-D` flag presence, this OS cannot install if the directory does not exist. (which seems to contradict the man page, but that's what it is)
When the directory is created first using `install -d`, then it's fine.

**Comment by SpotlightKid** [comment]
Works for me. I've been using this technique when installing things in AUR PKGBUILD files for a while now. 

```console
$ ls -la /usr/local/lib
insgesamt 8
drwxr-xr-x  2 root root 4096 18.08.2019 22:16 ./
drwxr-xr-x 11 root root 4096 02.03.2016 17:05 ../
$ touch foo
$ sudo install -Dm755 foo -t /usr/local/lib/vst
$ ls -la /usr/local/lib
insgesamt 12
drwxr-xr-x  3 root root 4096 18.08.2019 22:17 ./
drwxr-xr-x 11 root root 4096 02.03.2016 17:05 ../
drwxr-xr-x  2 root root 4096 18.08.2019 22:17 vst/
$ ls -la /usr/local/lib/vst/
insgesamt 8
drwxr-xr-x 2 root root 4096 18.08.2019 22:17 ./
drwxr-xr-x 3 root root 4096 18.08.2019 22:17 ../
-rwxr-xr-x 1 root root    0 18.08.2019 22:17 foo*
```

What does `install --version` report on your system? Mine says `install (GNU coreutils) 8.31`.

**Comment by jpcima** [comment]
`install (GNU coreutils) 8.21`

It's not "my" system, it's the "trusty" image from Travis-CI.
CI images are voluntarily kept back to produce the most compatible software builds.

I try to use `make install` to turn DPF builds to debian packages; under this context, the problem happens.

**Comment by SpotlightKid** [comment]
Can you test if this command would work on the Travis env?

```Makefile
ifeq ($(BUILD_VST2),true)
    install -Dm755 $(TARGET_DIR)/$(NAME)-vst$(LIB_EXT) $(DESTDIR)$(VST_DIR)/$(NAME)-vst$(LIB_EXT)
endif
```

**Comment by jpcima** [comment]
Yes, so I rolled back my repo to these install rules, I run inside docker, and I've removed @ signs to print the commands.

At first, this is seen:
```
make install -C plugins/stone-phaser;
make[1]: Entering directory `/root/stone-phaser/plugins/stone-phaser'
install -Dm755 ../../bin/stone-phaser-vst.so -t /usr/local/lib/vst
install: failed to access '/usr/local/lib/vst': No such file or directory
```

I change it as indicated. Then it's a success:
```
make install -C plugins/stone-phaser;
make[1]: Entering directory `/root/stone-phaser/plugins/stone-phaser'
install -Dm755 ../../bin/stone-phaser-vst.so /usr/local/lib/vst/stone-phaser-vst.so
make[1]: Leaving directory `/root/stone-phaser/plugins/stone-phaser'
```

**Comment by jpcima** [comment]
I confirm the new rules as working.
A working build: https://travis-ci.com/jpcima/stone-phaser/builds/123646553

**Comment by SpotlightKid** [comment]
You also need to copy the updated path variable definitions at the top of the makefile to make the `install-user` target work correctly.

**Comment by jpcima** [comment]
Oh you're right, I have missed it, thanks. I must not have used initially an updated version of the template.
